# Feign配置
feign:
    client:
        config:
            default:
                loggerLever: basic
    httpclient:  # 启用 httpclient，支持连接池技术
        enabled: true
        max-connections: 200
        max-connections-per-route: 50
