server:
  port: 8083
  servlet:
    context-path: /cooperation

spring:
  application:
    name: cooperation
  datasource:
    url: jdbc:mysql://localhost:3306/medi_mind?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 16MB
  quartz:
    jdbc:
      initialize-schema: never

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_effective
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    edu.hbmu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

sa-token:
  token-name: satoken
  timeout: 2592000
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  is-log: false