server:
  port: 8082
  servlet:
    context-path: /aidiagnosis  # 微服务统一路径

spring:
  application:
    name: aidiagnosis
  datasource:
    url: jdbc:mysql://localhost:3306/medi_mind?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
      auto-index: update
      open-in-view: false
      repositories:
        enabled: true
      embedded:
        enabled: true
      connection:
        pool:
          size: 100

logging:
  level:
    edu.hbmu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
